apiVersion: v1
kind: Service
metadata:
  name: nama-aplikasi-anda
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 32000
  selector:
    name: nama-aplikasi-anda